apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    role: myrole
spec:
  volumes:
    - name: app
      emptyDir: { }
  containers:
    - name: web
      image: artemseliv/test:1.0.1
      volumeMounts:
        - name: app
          mountPath: /app
      ports:
        - name: web
          containerPort: 8000
          protocol: TCP
  initContainers:
    - name: init-myservice
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app